### ISSUE TITLE
Browser extension?

### ISSUE THREAD

**Issue by andrews05** [niutech/jxl.js#3]
Just wondering out loud here, could this be implemented in a browser extension? It may not be practical to make users install an extension, but maybe it could perform better for those that do. 

[edit] As another thought, could there be a ‘lite’ version for transcoded jpegs only? It could be smaller and decode back to jpeg for better performance.

**Comment by niutech** [comment]
I've simplified JXL.js, now it decodes JXL to JPG images offscreen and caches them for subsequent page views.

Web extension would be useful if JXL images were more popular among websites. Injecting a content script and a Mutation Observer to every web page when JXL is a rarity makes no sense. For now JXL.js is aimed for those website authors who want to start serving JXL images to their users.
