### ISSUE TITLE
firefox?

### ISSUE THREAD

**Issue by farvardin** [niutech/jxl.js#4]
hello,

the sample page doesn't work in my firefox (version 106 and 107) on Linux mint. On an other computer it's the same. It doesn't work either in brave browser.  WASM is activated since this sample page is working for me: https://d2jta7o2zej4pf.cloudfront.net/

The only browser which worked for me was google chrome.

**Comment by niutech** [comment]
Sorry, but you should raise this issue to Adblocker Ultimate, possibly WASM is blocked by some of its filters.
