### ISSUE TITLE
Why config.imageType = 'jpeg'?

### ISSUE THREAD

**Issue by jackyhallyday** [niutech/jxl.js#8]
Hello,
I guess this option is there to save space if the cache is enabled, but it's a bit strange, since it's a lossy option.
Maybe it shouldn't be the default, or maybe it should be forced to PNG if config.useCache = false?
Is there any technical reason why JPEG should be used if the cache is disabled?

**Comment by niutech** [comment]
That's exactly the reason - to save the cache space. The default quality is 92%, so the loss shouldn't be noticeable. You can easily change image type to `png` or `webp` if you like while disabling cache.
